use_frameworks!

platform :ios, '9.0'

target 'LipengTestLibrary_Example' do
  pod 'LipengTestLibrary', :path => '../'

  target 'LipengTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
